# .github/workflows/pull_request_approval.yml
name: "PR Approval Workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  approval:
    runs-on: ubuntu-latest
    environment:
      name: prod  # Specify the environment, approval is required here
    steps:
      - name: Waiting for Approval
        run: echo "Waiting for manual approval..."
        # This step pauses until approval is granted by an authorized user
# .github/workflows/pull_request_approval.yml
